# Increase Starship command scan & duration time-outs
scan_timeout = 80
command_timeout = 1000

# Do not truncate the directory listing
#[directory]
#truncation_length = 0

# Show even very fast command durations in terminal (in ms)
[cmd_duration]
min_time = 5
show_milliseconds = true

